name: jsDelivr

on:
  push:
    branches:
      - main

jobs:
  purge-cdn:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Purge remove-branding-framer
        id: purgeRemoveBrandingFramer
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://purge.jsdelivr.net/gh/marcsigmund/js-scripts@latest/remove-branding-framer.js"
          method: "GET"

      - name: Purge plausible-ignore
        id: purgePlausibleIgnore
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://purge.jsdelivr.net/gh/marcsigmund/js-scripts@latest/plausible-ignore.js"
          method: "GET"

      - name: Purge link-params
        id: purgeLinkParams
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://purge.jsdelivr.net/gh/marcsigmund/js-scripts@latest/link-params.js"
          method: "GET"

      - name: Show Response
        run: |
          echo ${{ steps.purgeRemoveBrandingFramer.outputs.response }}
          echo ${{ steps.purgePlausibleIgnore.outputs.response }}
          echo ${{ steps.purgeLinkParams.outputs.response }}
