name: jsDelivr

on:
  push:
    branches:
      - main

jobs:
  purge-cdn:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Purge remove-branding-framer
<<<<<<< HEAD
        id: purgeRemoveBrandingFramer
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://purge.jsdelivr.net/gh/marcsigmund/js-scripts/remove-branding-framer.js"
          method: "GET"

      - name: Purge plausible-ignore
        id: purgePlausibleIgnore
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://purge.jsdelivr.net/gh/marcsigmund/js-scripts/plausible-ignore.js"
          method: "GET"

      - name: Purge keep-url-params
        id: purgeKeepUrlParams
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://purge.jsdelivr.net/gh/marcsigmund/js-scripts/keep-url-params.js"
          method: "GET"

      - name: Show Response
        run: |
          echo ${{ steps.purgeRemoveBrandingFramer.outputs.response }}
          echo ${{ steps.purgePlausibleIgnore.outputs.response }}
          echo ${{ steps.purgeKeepUrlParams.outputs.response }}
=======
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: "https://purge.jsdelivr.net/gh/marcsigmund/js-scripts/remove-branding-framer.js"
          webhook_secret: "-"

      - name: Purge plausible-ignore
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: "https://purge.jsdelivr.net/gh/marcsigmund/js-scripts/plausible-ignore.js"
          webhook_secret: "-"

      - name: Purge keep-url-params
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: "https://purge.jsdelivr.net/gh/marcsigmund/js-scripts/keep-url-params.js"
          webhook_secret: "-"
>>>>>>> 39263b99bfe43c4861504dc959aeeefe279bc9db
